### ISSUE TITLE
seed.evonet.networks.dash.org name not resolved

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/js-dash-sdk#57]
### Expected Behavior

seed.evonet.networks.dash.org  resolves to IP address

### Current Behavior

seed.evonet.networks.dash.org does not resolve

### Context

A number of users have reported an error with DNS name for seed.evonet.networks.dash.org resolving correctly in the client.
Some comments [here](https://discordapp.com/channels/670271785974890526/670599939528851476/705382564302684161) and [here](https://discordapp.com/channels/670271785974890526/687630641294344223/708402318650900530)

**Comment by antouhou** [comment]
Seems like the DNS record is resolved correctly:
```
ping seed.evonet.networks.dash.org
PING seed.evonet.networks.dash.org (34.211.141.125): 56 data bytes
```
Is there any update on this?

**Comment by cloudwheels** [comment]
Hi Anton, this one is very strange. Initially I thought it was just my
machine as I was also about to see that it resolves when using a service
outside my network. However, Andy Freer and @dashameter have both seen this
too.

My next thought was that it was Ubuntu related, as there is a similar issue
documented for some versions of Ubuntu (and I *think* both those guys might
use that too) but actually it occurs on other machines running different
distributions for me. Other IPs resolve fine, in fact this is the only time
I experience a DNS problem on my network.

My latest thought was that maybe it was an ISP block on 'undesirable'
content as it's a crypto network, but I can visit other dash.org domains
fine too.

It has to be a local network issue of some sort, but due to the fact that
others have experienced it I think it's worth keeping open as an issue
until it becomes clearer.

Will see if I can run more network tests to find out more...

**Comment by PastaPastaPasta** [comment]
It's resolving for me on ubuntu 18.04. Have you tried resolving over VPN or changing your DNS to 1.1.1.1 (cloudflare) or 8.8.8.8 (google)

**Comment by andyfreer** [comment]
Yes i'm getting this error constantly (ping seed.evonet.networks.dash.org not resolved)

Obvs not just my location either as proxy doesn't find it e.g. https://network-tools.com/

**Comment by thephez** [comment]
This is a weird one. I have no issue here. 

![image](https://user-images.githubusercontent.com/8145677/82054751-6a86dd80-968d-11ea-8f58-a45b8b8dd0a1.png)

And [https://mxtoolbox.com](https://mxtoolbox.com/SuperTool.aspx?action=a%3aseed.evonet.networks.dash.org&run=toolpage) returns results too. :thinking:

**Comment by cloudwheels** [comment]
Would it not be better practice anyway to split the A records over multiple
host /TLD names and list an array of seeds in the client?

**Comment by thephez** [comment]
There may be better ways to do it. But it is following the way Bitcoin/Dash/etc have done [seed nodes ](https://dashcore.readme.io/docs/core-guide-p2p-network-peer-discovery#section-dns-seeds) for years which makes me wonder if add more than one seed would actually change anything.

**Comment by cloudwheels** [comment]
Just to confirm (as expected) the same problem occurs with multiple host names , i.e. seed-1, seed-2 etc

**Comment by imanmousaei** [comment]
I have the same problem. I tried to ping these and I also got an error ( 'dash.org' works but 'seed.evonet.networks.dash.org' doesn't ) : 

![dash_network_not_resolved](https://user-images.githubusercontent.com/33493057/110208841-ac904280-7e9e-11eb-9396-6b8b78cbda01.PNG)

**Comment by shumkov** [comment]
Evonet is down in favor of testnet a month ago.

**Comment by imanmousaei** [comment]
so how can we connect to the mainnet?
@shumkov
